[package]
name = "bpe"
version = "0.1.0"
edition = "2024"

[dependencies]
boltffi = "0.29.3"
fancy-regex = "0.19.0"

[lib]
# see: https://doc.rust-lang.org/reference/linkage.html
# staticclib: create C like interface staticlly for other linaguages *.a file
# cdylib: Creates dynamic C like interfce dynamilly for other languages *.so, .dll files
# lib: stadaard rust build and format
crate-type = ["staticlib", "cdylib", "lib"]
